language: node_js
node_js:
  - "6.9.5"
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/install_selenium_standalone
  - java -jar selenium/selenium-server-standalone-2.35.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
  - sleep 3

script:
  - echo 'Hello Firebase'
  - protractor test/professorTest.js
